FROM node:16-alpine

WORKDIR '/app'

COPY package.json .
RUN npm install
RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache  
#https://stackoverflow.com/questions/67087735/eacces-permission-denied-mkdir-usr-app-node-modules-cache-how-can-i-creat

COPY . .
# e bom deixar apesar de nao precisar (devido a referencia no docker-compose.yml) e bom deixar como m lembrete p/ quando for criar o de producao

CMD ["npm", "run", "start"]